# --- Базовые настройки (на верхнем уровне) ---
# Это основная папка, куда будут попадать все обработанные файлы.
# Это обязательный параметр для режима авто-сортировки (-f).
target_folder: /app/processed_files

# Это папка, куда будут попадать файлы, если они не подошли
# ни под одно из правил сортировки ниже.
default_folder: /app/processed_files/default


# --- Правила сортировки по ключевым словам (вложенная структура) ---
# Эта секция используется для перемещения файлов в конкретные подпапки.
pypdfocr:
  filing:

    # Правило №1:
    - target_folder: /app/processed_files/invoices
      keywords:
        - счет
        - invoice
        - оплата

    # Правило №2:
    - target_folder: /app/processed_files/reports
      keywords:
        - отчет
        - report

    # Правило №3:
    - target_folder: /app/processed_files/evgeniy_docs
      keywords:
        - Евгений
        - AnyScanner
